name = "real-estate-note"
compatibility_date = "2024-02-08"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[[d1_databases]]
binding = "DB"
database_name = "real-estate-db"
database_id = "41599b93-23a2-4cc9-ad90-886be537058c"
